### ISSUE TITLE
Server fails to load on Release 1.0.1

### ISSUE THREAD

**Issue by JordanPlayz158** [WeiiswurstDev/PlaceStom#1]
On the latest release of the server, the server fails to start, I pinpointed the issue to the Teleport Command, line 13 looking for an integer of a system property, this is not specified in the README for running the server, here is the error:

```
Exception in thread "main" java.lang.ExceptionInInitializerError
        at dev.weiiswurst.placestom.PlaceServer.registerCommands(PlaceServer.java:106)
        at dev.weiiswurst.placestom.PlaceServer.main(PlaceServer.java:91)
Caused by: java.lang.NullPointerException: Cannot invoke "java.lang.Integer.intValue()" because the return value of "java.lang.Integer.getInteger(String)" is null
        at dev.weiiswurst.placestom.commands.TeleportCommand.<clinit>(TeleportCommand.java:13)
        ... 2 more
```
and the fix has multiple solutions, 1, have a default value, specify in the readme a system property is required or a few other options.

Here is an example, adding this to the java startup parameters:
`-Dplacestom.worldborder-size=4`

**Comment by ArvedEh** [comment]
In the default server.properties (src/main/resources/server.properties), the placestom.worldborder-size is defined and set to 500 as a default.

This file should automatically be placed in the running dir of the server unless there already was a server.properties file.

Does the server put the file in the current directory for you?

**Comment by ArvedEh** [comment]
Alright, just tested a fresh build in a new empty directory and can't reproduce the error you are getting. I have tested it on both linux and windows with fresh builds.

Did you modify any files? If so, could you please share them with me for debugging?

**Comment by JordanPlayz158** [comment]
Issue was caused by server.properties already existing, not the fault of the project.

**Comment by JordanPlayz158** [comment]
Here is the egg I used (have to upload as zip as for whatever reason github doesn't let you upload json files.) in case anyone running pterodactyl in the future has issues running this
[egg-minestom.json.zip](https://github.com/WeiiswurstDev/PlaceStom/files/8517212/egg-minestom.json.zip)
