### ISSUE TITLE
Issue when placing blocks, light levels not updated

### ISSUE THREAD

**Issue by JordanPlayz158** [WeiiswurstDev/PlaceStom#3]
I think I found an actual issue this time (hopefully), when placing a block in any of the chunks, the chunk becomes dark so I assume there are no light level chunk updates or they are not occurring correctly, I am running vanilla 1.18.2 on the client and when relogging, the light resets, here is a screenshot of what I mean:
https://cdn.jordanplayz158.xyz/uploads/be5793f44f02c69c2a046309912bb606c0a1b558.png

**Comment by ArvedEh** [comment]
I am usually playing on OptiFine 1.18.2 and have not had this issue. I will test it on vanilla as well now.

Have you changed anything, e.g. the block choices, or is it all default?

Also don't worry about the previous issues. If someone else runs it on Pterodactyl, they might run into the same  issue and get their problem solved :)

**Comment by ArvedEh** [comment]
Just checked on vanilla, running into the same issue. I should have tested it on vanilla right away, I just didn't think it would make any difference. I'll try to fix this now, nobody should have to use a different (closed-source) Minecraft version to play on the server.
Edit: This might not be an OptiFine thing after all, I just realized that I also used a mod to increase gamma levels previously, but changed back. Feels kinda dumb now because I never tested for lighting lol.

**Comment by ArvedEh** [comment]
Should be fixed with [the new commit, will be in 1.0.2](https://github.com/WeiiswurstDev/PlaceStom/commit/57e433194165810c1ce072809bbdba32b1a9bb12)

Please try the fix: Pull the master branch, rebuild and check if the lighting works now for you as well :)

**Comment by JordanPlayz158** [comment]
> I am usually playing on OptiFine 1.18.2 and have not had this issue. I will test it on vanilla as well now.
> 
> Have you changed anything, e.g. the block choices, or is it all default?
> 
> Also don't worry about the previous issues. If someone else runs it on Pterodactyl, they might run into the same issue and get their problem solved :)

Yeah speaking of which I'll upload my minestom egg to issue 1, have 2 refer to one and submit it to eggs repo for pterodactyl

> Just checked on vanilla, running into the same issue. I should have tested it on vanilla right away, I just didn't think it would make any difference. I'll try to fix this now, nobody should have to use a different (closed-source) Minecraft version to play on the server. Edit: This might not be an OptiFine thing after all, I just realized that I also used a mod to increase gamma levels previously, but changed back. Feels kinda dumb now because I never tested for lighting lol.

It's understandable I wouldn't assume vanilla would've made any difference either, no worries about not checking for lighting, I find impressive you made your own minestom server jar to begin with

> Should be fixed with [the new commit, will be in 1.0.2](https://github.com/WeiiswurstDev/PlaceStom/commit/57e433194165810c1ce072809bbdba32b1a9bb12)
> 
> Please try the fix: Pull the master branch, rebuild and check if the lighting works now for you as well :)

Will try within the hour

**Comment by ArvedEh** [comment]
Did it work?

**Comment by JordanPlayz158** [comment]
Fixed, sorry for the very long response time, thank you for the fix!
